### ISSUE TITLE
Remove vendor folder

### ISSUE THREAD

**Issue by danielgospodinow** [qbaware/kosher#27]
Because
* Difficulties with rebuilding/introducing new dependencies and fighting with VSCode because of that
* Changes to vendor make PRs big and ugly, thus harder to review
* No need for reproducible builds, the project uses stable dependencies
* Makes the repo more compact and clean
* Java and NodeJS have existed successfully without committing their libraries to VC so this project should be good too

@HakanSunay

**Comment by HakanSunay** [comment]
Halal issue
